export const FETCH_QUESTION_DATA = "FETCH_QUESTION_DATA";
export const FETCH_LABELS_DATA = "FETCH_LABELS_DATA";
export const FETCH_QUESTION_DATA_SUCCESS = "FETCH_QUESTION_DATA_SUCCESS";
export const FETCH_LABELS_DATA_SUCCESS = "FETCH_LABELS_DATA_SUCCESS";
export const LABELS_LOCALSTORAGE_KEY = "LABELS_DATA";
export const QUESTIONS_LOCALSTORAGE_KEY = "QUESTIONS_DATA";
